### ISSUE TITLE
add groovy 3 support

### ISSUE THREAD

**Issue by the3ver** [jenkinsci/groovy-sandbox#62]
Is there a plan to support groovy 3.x ?

**Comment by dwnusbaum** [comment]
No, there is no plan to support Groovy 3.x. Upgrading Groovy is problematic because this project is closely tied to Groovy implementation details that can change between releases, and because new features added in newer versions of Groovy may allow the sandbox to be bypassed. We'd need to do a comprehensive review of all changes between Groovy 2.4.12 and the proposed version to make sure that the sandbox still works as expected and make any necessary changes.
